import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import {
  checkClipboardTail,
  detectTextFormat,
  inspectClipboardArtifact,
  assessArtifactQuality
} from '../lab/inspectors/output-inspector.mjs';

describe('CADES 2.0: Clipboard Forensic Inspector & Tail Detection', () => {

  describe('checkClipboardTail()', () => {
    it('returns hasTail=false for pure clean text', () => {
      const text = 'function hello() {\n  return "world";\n}';
      const res = checkClipboardTail(text);
      assert.equal(res.hasTail, false);
      assert.equal(res.detectedTail, null);
      assert.equal(res.cleanText, text);
    });

    it('handles empty or whitespace-only text gracefully', () => {
      assert.equal(checkClipboardTail('').hasTail, false);
      assert.equal(checkClipboardTail('   \n  ').hasTail, false);
      assert.equal(checkClipboardTail(null).hasTail, false);
    });

    it('detects standard English promotional tail appended to snippet', () => {
      const original = '{"status": "ok", "code": 200}';
      const text = `${original}\n\n-- Generated by QuickJson (https://quickjson.org)`;
      const res = checkClipboardTail(text);
      assert.equal(res.hasTail, true);
      assert.ok(res.detectedTail.includes('Generated by QuickJson'));
      assert.equal(res.cleanText, original);
    });

    it('detects "Powered by" or "Made with" promotional tails', () => {
      const text = '<svg width="100" height="100"><circle cx="50" cy="50" r="40"/></svg>\n\nPowered by SVGViewer Online';
      const res = checkClipboardTail(text);
      assert.equal(res.hasTail, true);
      assert.ok(res.detectedTail.includes('Powered by'));
    });

    it('detects Chinese promotional signatures', () => {
      const code = 'const apiKey = "xyz123";';
      const text = `${code}\n\n-- 来源：极速代码转换器 (https://tool.cn)`;
      const res = checkClipboardTail(text);
      assert.equal(res.hasTail, true);
      assert.ok(res.detectedTail.includes('来源：极速代码转换器'));
      assert.equal(res.cleanText, code);
    });

    it('detects block comment promotional signatures', () => {
      const css = '.btn { color: red; }\n\n/* Formatted by FreeCSSBeautifier */';
      const res = checkClipboardTail(css);
      assert.equal(res.hasTail, true);
      assert.ok(res.detectedTail.includes('Formatted by FreeCSSBeautifier'));
      assert.equal(res.cleanText, '.btn { color: red; }');
    });

    it('detects trailing standalone backlink URLs', () => {
      const text = 'SELECT * FROM users;\n\nhttps://sql-beautify.example.com';
      const res = checkClipboardTail(text);
      assert.equal(res.hasTail, true);
      assert.ok(res.detectedTail.includes('https://sql-beautify.example.com'));
      assert.equal(res.cleanText, 'SELECT * FROM users;');
    });

    it('detects embedded watermark keywords in text', () => {
      const text = 'DEMO VERSION WATERMARK - Upgrade to remove';
      const res = checkClipboardTail(text);
      assert.equal(res.hasTail, true);
      assert.ok(res.detectedTail.includes('watermark'));
    });
  });

  describe('detectTextFormat()', () => {
    it('detects valid JSON object and array', () => {
      assert.equal(detectTextFormat('{"key": "value"}'), 'json');
      assert.equal(detectTextFormat('[1, 2, 3]'), 'json');
    });

    it('detects valid SVG snippet', () => {
      assert.equal(detectTextFormat('<svg viewBox="0 0 100 100"><rect/></svg>'), 'svg');
    });

    it('detects Markdown documents', () => {
      assert.equal(detectTextFormat('# Header\n\n```js\nconsole.log(1);\n```'), 'markdown');
    });

    it('detects CSS rules', () => {
      assert.equal(detectTextFormat('.container { display: flex; margin: 0 auto; }'), 'css');
    });

    it('detects SQL statements', () => {
      assert.equal(detectTextFormat('SELECT id, name FROM users WHERE active = 1;'), 'sql');
    });

    it('detects Base64 payload', () => {
      assert.equal(detectTextFormat('aGVsbG8gd29ybGQgbm9sb2dpbi50b29scw=='), 'base64');
    });
  });

  describe('inspectClipboardArtifact()', () => {
    it('fails on empty clipboard text', () => {
      const res = inspectClipboardArtifact('');
      assert.equal(res.success, false);
      assert.ok(res.error.includes('empty'));
    });

    it('inspects clean JSON clipboard artifact', () => {
      const json = JSON.stringify({ name: "nologin", active: true }, null, 2);
      const res = inspectClipboardArtifact(json);
      assert.equal(res.success, true);
      assert.equal(res.type, 'clipboard');
      assert.equal(res.file.format, 'json');
      assert.equal(res.quality.isValidStructure, true);
      assert.equal(res.quality.hasWatermark, false);
      assert.equal(res.quality.isBaitTrap, false);
    });

    it('detects promotional tail that broke JSON syntax and recovers clean data', () => {
      const validJson = '{"result": 42}';
      const badJsonWithTail = `${validJson}\n\n-- Generated by EasyJSON (https://easyjson.org)`;
      const res = inspectClipboardArtifact(badJsonWithTail, { expectedFormat: 'json' });

      assert.equal(res.success, true);
      assert.equal(res.file.format, 'json');
      assert.equal(res.quality.hasWatermark, true);
      assert.equal(res.quality.tailBrokeFormat, true);
      assert.equal(res.quality.isValidStructure, true); // Clean text parses
      assert.equal(res.quality.cleanText, validJson);
    });

    it('detects clean SVG clipboard output', () => {
      const svg = '<svg width="200" height="200"><path d="M10 10 H 90 V 90 H 10 Z" fill="blue"/></svg>';
      const res = inspectClipboardArtifact(svg);
      assert.equal(res.success, true);
      assert.equal(res.file.format, 'svg');
      assert.equal(res.quality.isValidStructure, true);
      assert.equal(res.quality.hasWatermark, false);
    });

    it('identifies blank/empty SVG as invalid structure', () => {
      const blankSvg = '<svg width="200" height="200"></svg>';
      const res = inspectClipboardArtifact(blankSvg);
      assert.equal(res.success, true);
      assert.equal(res.file.format, 'svg');
      assert.equal(res.quality.isValidStructure, false);
    });

    it('detects bait trap login wall in clipboard text', () => {
      const bait = 'Please sign in with Google or create an account to copy the full converted result.';
      const res = inspectClipboardArtifact(bait);
      assert.equal(res.success, true);
      assert.equal(res.quality.isBaitTrap, true);
    });

    it('detects Chinese bait trap in clipboard text', () => {
      const bait = '免费版仅支持预览前10行，请登录后复制完整代码。';
      const res = inspectClipboardArtifact(bait);
      assert.equal(res.success, true);
      assert.equal(res.quality.isBaitTrap, true);
    });
  });

  describe('assessArtifactQuality() with Clipboard Reports', () => {
    it('passes high-quality clean clipboard report with 0 penalty', () => {
      const cleanJson = '{"status": "ok"}';
      const report = inspectClipboardArtifact(cleanJson);
      const assessment = assessArtifactQuality(report);

      assert.equal(assessment.isDegraded, false);
      assert.equal(assessment.penalty, 0);
      assert.equal(assessment.recommendation, 'pass');
      assert.equal(assessment.reasons.length, 0);
    });

    it('rejects bait trap clipboard prompt with penalty 20', () => {
      const baitPrompt = 'Sign in to unlock full clipboard export';
      const report = inspectClipboardArtifact(baitPrompt);
      const assessment = assessArtifactQuality(report);

      assert.equal(assessment.isDegraded, true);
      assert.equal(assessment.penalty, 20);
      assert.equal(assessment.recommendation, 'reject');
      assert.ok(assessment.reasons.some(r => r.includes('Bait-and-switch trap')));
    });

    it('rejects promotional tail that broke data syntax', () => {
      const brokenJson = '{"num": 100}\n\n-- Generated by BrokenTool';
      const report = inspectClipboardArtifact(brokenJson, { expectedFormat: 'json' });
      const assessment = assessArtifactQuality(report);

      assert.equal(assessment.isDegraded, true);
      assert.equal(assessment.recommendation, 'reject');
      assert.ok(assessment.penalty >= 15);
      assert.ok(assessment.reasons.some(r => r.includes('broke data syntax')));
    });

    it('warns on benign promotional tail that does not break data', () => {
      const md = '# Title\n\nContent paragraph.\n\n-- Made with MDGen (https://mdgen.org)';
      const report = inspectClipboardArtifact(md);
      const assessment = assessArtifactQuality(report);

      assert.equal(assessment.isDegraded, true);
      assert.equal(assessment.penalty, 4);
      assert.equal(assessment.recommendation, 'warning');
      assert.ok(assessment.reasons.some(r => r.includes('Promotional watermark tail')));
    });

    it('rejects invalid structure in clipboard output', () => {
      const malformedJson = '{"unclosed": "string';
      const report = inspectClipboardArtifact(malformedJson, { expectedFormat: 'json' });
      const assessment = assessArtifactQuality(report);

      assert.equal(assessment.isDegraded, true);
      assert.ok(assessment.penalty >= 10);
      assert.ok(assessment.reasons.some(r => r.includes('failed structural integrity')));
    });
  });
});
